spring:
  config:
    import: optional:classpath:env.development.yml
  datasource:
    url: ${app.database.url}
    username: ${app.database.username}
    password: ${app.database.password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      "[hibernate.format_sql]": true
    open-in-view: false

  servlet.multipart:
    max-file-size: 20MB
    max-request-size: 20MB
    location: ${java.io.tmpdir}

  jackson:
    default-property-inclusion: non-null
    
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${app.firebase.jwk-set-uri}
          issuer-uri: ${app.firebase.issuer-uri}


springdoc:
  packages-to-scan:
    - com.marketplace.api.admin
    - com.marketplace.api.consumer
    - com.marketplace.api.vendor
    - com.marketplace.api.payment
  paths-to-match:
    - /api/**
  swagger-ui:
    enabled: true
    path: /api-docs-ui
  api-docs:
    enabled: true

logging:
  level:
    tracer: off
    "[org.springframework.data.auditing.AuditingHandlerSupport]": DEBUG
    "[org.springframework.data.auditing.AuditingHandler]": DEBUG
    "[org.springframework.web.client.RestTemplate]": DEBUG
    "[org.springframework.web.client.DefaultRestClient]": DEBUG
    "[org.springframework.web.servlet.DispatcherServlet]": DEBUG
